"""Critical warnings that may invalidate or reduce the accuracy of a tax statement.

These warnings are generated by importers and calculator phases to inform the
user about issues that need attention.  They are rendered on the instructions
page of the PDF and a hint is placed on the summary page.
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class CriticalWarningCategory(str, Enum):
    """Category of a critical warning."""

    MISSING_KURSLISTE = "missing_kursliste"
    STOCK_SPLIT_MISMATCH = "stock_split_mismatch"
    UNMAPPED_SYMBOL = "unmapped_symbol"
    PREVIOUS_YEAR_EXDATE = "previous_year_exdate"
    OTHER = "other"


class CriticalWarning(BaseModel):
    """A single critical warning attached to a tax statement.

    Attributes:
        category: The category/type of warning.
        message: Human-readable description of the problem.
        source: Which phase or component generated this warning
                (e.g. ``"KurslisteTaxValueCalculator"``).
        identifier: Optional identifier of the affected security/position.
    """

    category: CriticalWarningCategory
    message: str
    source: str
    identifier: Optional[str] = None
