"""Tests for critical warnings generated by CleanupCalculator for unmapped symbols."""

from datetime import date, datetime
from decimal import Decimal

import pytest

from opensteuerauszug.calculate.cleanup import CleanupCalculator
from opensteuerauszug.model.critical_warning import CriticalWarningCategory
from opensteuerauszug.model.ech0196 import (
    Depot,
    DepotNumber,
    ISINType,
    ListOfSecurities,
    Security,
    SecurityStock,
    SecurityTaxValue,
    TaxStatement,
)


def _make_statement_with_symbol(symbol, isin=None, valor=None, name="Test Security"):
    """Create a minimal TaxStatement with one security that has a symbol."""
    security = Security(
        positionId=1,
        isin=ISINType(isin) if isin else None,
        valorNumber=valor,
        securityName=name,
        securityCategory="SHARE",
        country="US",
        currency="USD",
        quotationType="PIECE",
        symbol=symbol,
        stock=[
            SecurityStock(
                referenceDate=date(2024, 1, 1),
                mutation=False,
                quantity=Decimal("10"),
                balanceCurrency="USD",
                quotationType="PIECE",
            ),
        ],
        taxValue=SecurityTaxValue(
            referenceDate=date(2024, 12, 31),
            quotationType="PIECE",
            quantity=Decimal("10"),
            balanceCurrency="USD",
        ),
    )
    return TaxStatement(
        minorVersion=2,
        id="test-cleanup-warnings",
        creationDate=datetime(2024, 6, 1),
        taxPeriod=2024,
        periodFrom=date(2024, 1, 1),
        periodTo=date(2024, 12, 31),
        country="CH",
        canton="ZH",
        totalTaxValue=Decimal("0"),
        totalGrossRevenueA=Decimal("0"),
        totalGrossRevenueB=Decimal("0"),
        totalWithHoldingTaxClaim=Decimal("0"),
        listOfSecurities=ListOfSecurities(
            depot=[Depot(depotNumber=DepotNumber("D1"), security=[security])]
        ),
    )


def test_unmapped_symbol_generates_critical_warning():
    """A symbol not found in the identifier map produces a critical warning."""
    identifier_map = {}  # empty map - nothing can be resolved
    calculator = CleanupCalculator(
        period_from=date(2024, 1, 1),
        period_to=date(2024, 12, 31),
        identifier_map=identifier_map,
        importer_name="schwab",
    )
    statement = _make_statement_with_symbol(symbol="GOOG", isin=None, valor=None)
    result = calculator.calculate(statement)

    warnings = [
        w for w in result.critical_warnings
        if w.category == CriticalWarningCategory.UNMAPPED_SYMBOL
    ]
    assert len(warnings) == 1
    assert "GOOG" in warnings[0].message
    assert warnings[0].identifier == "GOOG"
    assert warnings[0].source == "CleanupCalculator"


def test_mapped_symbol_generates_no_warning():
    """A symbol that IS in the identifier map does not produce a warning."""
    identifier_map = {
        "GOOG": {"isin": "US02079K3059", "valor": 12345},
    }
    calculator = CleanupCalculator(
        period_from=date(2024, 1, 1),
        period_to=date(2024, 12, 31),
        identifier_map=identifier_map,
        importer_name="schwab",
    )
    statement = _make_statement_with_symbol(symbol="GOOG", isin=None, valor=None)
    result = calculator.calculate(statement)

    warnings = [
        w for w in result.critical_warnings
        if w.category == CriticalWarningCategory.UNMAPPED_SYMBOL
    ]
    assert len(warnings) == 0


def test_symbol_with_existing_isin_generates_no_warning():
    """A symbol that already has an ISIN does not produce a warning."""
    calculator = CleanupCalculator(
        period_from=date(2024, 1, 1),
        period_to=date(2024, 12, 31),
        identifier_map={},
        importer_name="schwab",
    )
    statement = _make_statement_with_symbol(
        symbol="GOOG", isin="US02079K3059", valor=None
    )
    result = calculator.calculate(statement)

    warnings = [
        w for w in result.critical_warnings
        if w.category == CriticalWarningCategory.UNMAPPED_SYMBOL
    ]
    assert len(warnings) == 0


def test_no_identifier_map_generates_no_unmapped_warning():
    """When no identifier map is provided, no unmapped-symbol warnings are generated.

    The enrichment block is skipped entirely when identifier_map is None, but the
    unmapped-symbol check should still work (the symbol has no ISIN but the map
    was not available, so we don't warn about missing mappings).
    """
    calculator = CleanupCalculator(
        period_from=date(2024, 1, 1),
        period_to=date(2024, 12, 31),
        identifier_map=None,
        importer_name="schwab",
    )
    statement = _make_statement_with_symbol(symbol="GOOG", isin=None, valor=None)
    result = calculator.calculate(statement)

    warnings = [
        w for w in result.critical_warnings
        if w.category == CriticalWarningCategory.UNMAPPED_SYMBOL
    ]
    # No identifier_map provided, but the symbol check still runs
    # Since the security has no ISIN and no valor, it should still warn
    assert len(warnings) == 1
