"""Tests for critical warnings generated by calculators."""

import datetime as dt
from datetime import date, datetime
from decimal import Decimal

import pytest

from opensteuerauszug.calculate.base import CalculationMode
from opensteuerauszug.calculate.kursliste_tax_value_calculator import KurslisteTaxValueCalculator
from opensteuerauszug.core.kursliste_exchange_rate_provider import KurslisteExchangeRateProvider
from opensteuerauszug.core.kursliste_manager import KurslisteManager
from opensteuerauszug.core.kursliste_accessor import KurslisteAccessor
from opensteuerauszug.model.critical_warning import CriticalWarningCategory
from opensteuerauszug.model.ech0196 import (
    Depot,
    DepotNumber,
    ISINType,
    ListOfSecurities,
    Security,
    SecurityStock,
    SecurityTaxValue,
    TaxStatement,
)
from opensteuerauszug.model.kursliste import (
    ExchangeRateYearEnd,
    Kursliste,
    Share,
)


def _make_statement_with_security(isin="US0000000000", valor=None, name="Test Security"):
    """Create a minimal TaxStatement with one security."""
    security = Security(
        positionId=1,
        isin=ISINType(isin) if isin else None,
        valorNumber=valor,
        securityName=name,
        securityCategory="SHARE",
        country="US",
        currency="USD",
        quotationType="PIECE",
        stock=[
            SecurityStock(
                referenceDate=date(2024, 1, 1),
                mutation=False,
                quantity=Decimal("10"),
                balanceCurrency="USD",
                quotationType="PIECE",
            ),
        ],
        taxValue=SecurityTaxValue(
            referenceDate=date(2024, 12, 31),
            quotationType="PIECE",
            quantity=Decimal("10"),
            balanceCurrency="USD",
        ),
    )
    return TaxStatement(
        minorVersion=2,
        id="test-calc-warnings",
        creationDate=datetime(2024, 6, 1),
        taxPeriod=2024,
        periodFrom=date(2024, 1, 1),
        periodTo=date(2024, 12, 31),
        country="CH",
        canton="ZH",
        totalTaxValue=Decimal("0"),
        totalGrossRevenueA=Decimal("0"),
        totalGrossRevenueB=Decimal("0"),
        totalWithHoldingTaxClaim=Decimal("0"),
        listOfSecurities=ListOfSecurities(
            depot=[Depot(depotNumber=DepotNumber("D1"), security=[security])]
        ),
    )


def _make_base_kursliste(shares=None):
    """Create a Kursliste for 2024 with a USD exchange rate and optional shares."""
    return Kursliste(
        version="2.2.0.0",
        creationDate=dt.datetime(2024, 12, 31),
        year=2024,
        shares=shares or [],
        exchangeRatesYearEnd=[
            ExchangeRateYearEnd(currency="USD", year=2024, value=Decimal("0.85")),
        ],
    )


def _make_provider(kursliste):
    """Wrap a Kursliste into a KurslisteExchangeRateProvider."""
    manager = KurslisteManager()
    manager.kurslisten[2024] = KurslisteAccessor(
        data_source=[kursliste], tax_year=2024
    )
    return KurslisteExchangeRateProvider(manager)


def test_missing_kursliste_entry_generates_critical_warning():
    """When a security is not found in the Kursliste, a critical warning is added."""
    provider = _make_provider(_make_base_kursliste(shares=[]))
    calculator = KurslisteTaxValueCalculator(
        mode=CalculationMode.OVERWRITE,
        exchange_rate_provider=provider,
    )
    statement = _make_statement_with_security(isin="US0000000000", name="Unknown Corp")
    result = calculator.calculate(statement)

    assert len(result.critical_warnings) == 1
    warning = result.critical_warnings[0]
    assert warning.category == CriticalWarningCategory.MISSING_KURSLISTE
    assert "Unknown Corp" in warning.message
    assert warning.identifier == "Unknown Corp"
    assert warning.source == "KurslisteTaxValueCalculator"


def test_found_kursliste_entry_generates_no_warning():
    """When the security IS in the Kursliste, no warning is generated."""
    share = Share(
        id=1,
        institutionId=1,
        institutionName="Test Institution",
        valorNumber=12345,
        isin="US0000000000",
        securityName="Known Corp",
        country="US",
        currency="USD",
        securityGroup="SHARE",
    )
    provider = _make_provider(_make_base_kursliste(shares=[share]))

    calculator = KurslisteTaxValueCalculator(
        mode=CalculationMode.OVERWRITE,
        exchange_rate_provider=provider,
    )
    statement = _make_statement_with_security(isin="US0000000000", name="Known Corp")
    result = calculator.calculate(statement)

    assert len(result.critical_warnings) == 0
